#!/bin/bash

#### CONSTANTS
JAR_VERSION="1.7.0"
JAR_NAME="stac-plugin-$JAR_VERSION-shaded.jar"

USER_HOST="root@vm-perf.cloud-espace.si.c-s.fr"
USER_PWD="password" # change me !

VMPERF_PATH="/DATA/sandbox/vm-perf/"
VMPERF_CATALOG_PATH="$VMPERF_PATH/workspace/regards/plugins/catalog"

#### COMMANDS
case $1 in
build)
    mvn clean install -DskipTests=true
;;
deploy)
    sshpass -p "$USER_PWD" scp "./stac-plugin/target/$JAR_NAME" "$USER_HOST:$VMPERF_CATALOG_PATH/"
;;
undeploy)
    sshpass -p "$USER_PWD" ssh "$USER_HOST" "rm -f $VMPERF_CATALOG_PATH/$JAR_NAME"
;;
catalog)
    case $2 in
    reboot)
        sshpass -p "$USER_PWD" ssh "$USER_HOST" "$VMPERF_PATH/cli/reboot.sh rs-catalog"
    ;;
    logs)
        sshpass -p "$USER_PWD" ssh "$USER_HOST" "$VMPERF_PATH/cli/logs.sh rs-catalog -f"
    ;;
    esac
;;
esac
